spring.application.name=authentification
# -------------------------
# Configuration de la bdd MySQL
# -------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/auth_bdd?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Niveau de log
logging.level.com.projetAuthentification=INFO

# Nom du fichier log
logging.file.name=logs/authentification.log

# Format simple
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

# Server Master Key (SMK)
app.smk=UneCleSuperSecreteDeMinimum32Car!!

# Parametres du protocole HMAC
# Fenetre de validite du timestamp en secondes (+-60s autour de l'heure actuelle)
app.auth.timestamp-window=60
# Duree de vie d'un nonce en secondes (120s = 2 minutes)
app.auth.nonce-ttl=120
# Duree de vie de l'access token en minutes
app.auth.token-ttl=15