name: CI Build Test Sonar Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Télécharger le code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Étape 2 : Installer Java 17
      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Étape 3 : Cache Maven
      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Étape 4 : Compiler le projet
      - name: Build project
        env:
          APP_MASTER_KEY: test_master_key_for_ci_only_32chars!
        run: mvn clean package

      # Étape 5 : Exécuter les tests
      - name: Run tests
        env:
          APP_MASTER_KEY: test_master_key_for_ci_only_32chars!
        run: mvn test

      # Étape 6 : Analyse SonarCloud
      - name: SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN:  ${{ secrets.SONAR_TOKEN }}
          APP_MASTER_KEY: test_master_key_for_ci_only_32chars!
        run: mvn sonar:sonar -Dsonar.qualitygate.wait=true

      # Étape 7 : Construire l'image Docker
      - name: Build Docker image
        run: docker build -t cdwfs-auth-app .